
spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    open-in-view: false
    database: postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.6:5432/thingsboard3.2
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 8
server:
  port: 8082
